
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DevAndres
 */
public class frmInicial extends javax.swing.JFrame {

    /**
     * Creates new form frmInicial
     */
    public frmInicial() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPing = new javax.swing.JButton();
        BtnPingN = new javax.swing.JButton();
        BtnPingL = new javax.swing.JButton();
        BtnPingT = new javax.swing.JButton();
        BtnDetener = new javax.swing.JButton();
        txtDir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResponse = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPing.setText("Ping");
        BtnPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPingActionPerformed(evt);
            }
        });

        BtnPingN.setText("Ping -n");
        BtnPingN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPingNActionPerformed(evt);
            }
        });

        BtnPingL.setText("Ping -l");
        BtnPingL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPingLActionPerformed(evt);
            }
        });

        BtnPingT.setText("Ping -t");
        BtnPingT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPingTActionPerformed(evt);
            }
        });

        BtnDetener.setText("Detener");
        BtnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetenerActionPerformed(evt);
            }
        });

        txtDir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDir.setToolTipText("192.168.0.101 / www.google.com");

        txaResponse.setEditable(false);
        txaResponse.setColumns(20);
        txaResponse.setRows(5);
        jScrollPane1.setViewportView(txaResponse);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Universidad Técnica del Norte");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre: Guacanes Kevin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre: Guacanes Kevin");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Carrera: Software");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Aplicacion para realizar pruebas de Ping");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese IP/Nombre de Dominio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(BtnPing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPingN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPingL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPingT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDetener)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPing)
                    .addComponent(BtnPingN)
                    .addComponent(BtnPingL)
                    .addComponent(BtnPingT)
                    .addComponent(BtnDetener)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Objeto que representa el proceso de ping en segundo plano
    private Process procesoPing;

    // Bandera para controlar si se debe detener el proceso de ping
    private boolean detenerPing = false;

    // Método para iniciar un proceso de ping con un comando
    private void Proceso(String comando) {
        try {
            // Ejecutar el comando en un hilo separado
            Thread pingThread = new Thread(() -> {
                try {
                    // Ejecuta el comando "ping" en el sistema operativo
                    procesoPing = Runtime.getRuntime().exec("ping " + comando);

                    // Lee la salida del proceso de ping
                    BufferedReader lector = new BufferedReader(new InputStreamReader(procesoPing.getInputStream()));
                    String linea;

                    // Mientras no se deba detener el proceso y haya líneas de salida
                    while (!detenerPing && (linea = lector.readLine()) != null) {
                        System.out.println(linea);
                        // Actualiza el JTextArea en el hilo EDT
                        actualizarTextArea(linea);
                    }

                    // Finaliza el proceso de ping
                    procesoPing.destroy();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });

            // Inicia el hilo de ping
            pingThread.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Método para actualizar el JTextArea en el hilo EDT
    private void actualizarTextArea(String linea) {
        SwingUtilities.invokeLater(() -> {
            txaResponse.append(linea + "\n");
        });
    }

    // Método para detener el proceso ping en segundo plano
    private void detenerPing() {
        detenerPing = true;
        if (procesoPing != null) {
            procesoPing.destroy();
        }
    }

    private void Mostrar(String linea) {
        txaResponse.setText(linea + "\n");
    }


    private void BtnPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPingActionPerformed
        String com = txtDir.getText();
        if (txtDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Direccion IP ó Nombre de Dominio");
        } else {
            Proceso(com);
        }
    }//GEN-LAST:event_BtnPingActionPerformed

    private void BtnPingNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPingNActionPerformed
        String com = txtDir.getText();
        if (txtDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Direccion IP ó Nombre de Dominio");
        } else {
            String input = JOptionPane.showInputDialog("Por favor, ingrese un número del 1 al 4294967295:");
            int numero = Integer.parseInt(input);
            Proceso("-n " + numero + " " + com);
        }
    }//GEN-LAST:event_BtnPingNActionPerformed

    private void BtnPingLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPingLActionPerformed
        String com = txtDir.getText();
        if (txtDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Direccion IP ó Nombre de Dominio");
        } else {
            String input = JOptionPane.showInputDialog("Por favor, ingrese el tamaño del paquete en bytes: ");
            int numero = Integer.parseInt(input);
            Proceso("-l " + numero + " " + com);
        }
    }//GEN-LAST:event_BtnPingLActionPerformed

    private void BtnPingTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPingTActionPerformed
        String com = txtDir.getText();
        if (txtDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Direccion IP ó Nombre de Dominio");
        } else {
            Proceso("-t " + com);
        }
    }//GEN-LAST:event_BtnPingTActionPerformed

    private void BtnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetenerActionPerformed
        detenerPing();
        this.dispose();
        frmInicial frmnuevo = new frmInicial();
        frmnuevo.show();
    }//GEN-LAST:event_BtnDetenerActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txaResponse.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDetener;
    private javax.swing.JButton BtnPing;
    private javax.swing.JButton BtnPingL;
    private javax.swing.JButton BtnPingN;
    private javax.swing.JButton BtnPingT;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResponse;
    private javax.swing.JTextField txtDir;
    // End of variables declaration//GEN-END:variables
}
